[[constraint]]
name = "github.com/aws/aws-lambda-go"
version = "1.4.0"

[[constraint]]
name = "github.com/aws/aws-sdk-go"
version = "1.15.10"

[[constraint]]
branch = "master"
name = "golang.org/x/sync"

[prune]
go-tests = true
unused-packages = true


